language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: OnBM4qv8u2+NOmBrRT8V4K62L7iyWhulTSwkv02HP6x9sUMEGmJVRHlr9kle7l5v7cFGxwogNCy4liZaS/5mMBrz5dR0CzDJsewo5T78OZM69dahwgtuHVcAOQ39u09GLQ/viglo0sLSxcNfJ5YYsscn38Gej5XaX/u2kNpISJb5QNMWte1Qm1Cy9ogmTwBErLC26Y6Vc8GA0egvbSeobU6Z15Pe/keTkC9zEtTfYC2N9J1hSaX6HFJKPCY+KquXPTr0d5oZvs1/9Lw9QoUUL+sE81BaoCLbqgHxKE7RYyXXZ0V/VwE73ns2eCfZBrC7E5tS51Z/OuRvx9Jr2N6iAZs6DWnA8jra8PrSSIZQe1LSMHB077ZAWOqph2ncGklaeekFasArj7vonXdUUy3jN0+htesvjeMny50i3iU4UM78LKaajxHzolSPVaLTQPVe2eHv1q0ifGcATQ+hekZyxHHbICvdt8tA75pKcVL9xqi/x7kHqi+/KMjVNIJanIQpwSl0PZ00j9eyJT5ox4OunkGYqCFCg5oMPRVeXvFcyxhVI0hH7RV95XFcTMadc9G1XqxEGBQSbpdb9WD/BjmwGuobb/oKNm1/AQwZZ22vlDzSX1GpHn5l14DClMrjsjXssjloDITXAanaWiD83rg2suQQzXsPw98evMhINaKa0Xo=
  app: habitualize-api
  on:
    repo: jrvscm/habitualize-api
