language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: JV6nwqfIJyqoNbA9YD8Nd7z67iz3O6ISRtApYO9IuFBxRmWUv5fVzS6TNot3X3xVs9bNuU9rzqRICehBGQ/mDFERX7udQZCsQUgHplbAHvCJdQ8le8EbzUZZEQ7qiMkzJZ2lUwewUZm4VNfoAt3ZxSpzWY+GFabmiT7LwdB8sGVzOL69fmOqgLkPXvr5oOO6hFEURx1koAjxSg2dxKlap3I/tnUzXLvWQqWoyNDt3xg9uTzlwgxsvIePmQk98S2zypq7t/TZ4o43cloTMMCIcJBpJylkGO3x0ICovQNMh+GAhyrBdHUqJma+KFuyD1lgpUjmez2eRnf112E+GFAza0HP19Cf6SAyhDoUIMJi4gIoRO48pvlZ+y4dcMBut7kkr6JcCbJqk6HOyp5GysaYWGK+zHh9GkJbgarPleOSsaymFKMnunQgAAzk0fI7rlcofoIfUbDdZe9w2AYsaUpPL4oFUAR2p2DE6MGzGxYEZg5AAKqpqkHGoX63Zx+Vx+eOUN0D91sfw2AJIaMdiJqIcc66lHozODQ2VstCNKj7ijim2GBZapr4MR/0dpD//dWoO3YpEkEYNOUu6uDwu4gpI8n6saBITuCAu+Va+fT3KNB+VACJsmi0iV/DJblrvXEmQgluPfiHHWpA+74QxauBvHZ3A7qpNZLCz9s4OJRwepA=
  app: habitualize-api
  on:
    repo: jrvscm/habitualize-api
