before_script: chmod 0777 ./node_modules/.bin/mocha
language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Z904+q0kpoJmEmdqsZHl4B1kQrRNst31XAccKaAke3vYCMiBvyppacSICLGXm8uJ1A2C/miqMsM4f/KOWFJ2OP6i72G1eIeYSrVLcwmnsJ+iGYghKl+BLy0RLVP1LvnASik8DzYdd1hbZQVOo0xRXhnnEJPjf0iMH6d94rHJKIOnPkAF0K5AY9eUK12KgNt6IJ0vzM0MH+2+hoDzbweOO3HuWgjUz4TZ107SSgEV1Jg1vcEWPP/JNpcK71LBLM1kr7FSrOsLlfUbdNKDVrDQAxE1Uhq1LNf56Wg7C8Fq27DCxDj3hDBWdEOr7h6N+cDhSrIZTZl+J8kyeXQhvUyr/1a25npX8AoHyv1I7ZIBGzfn+WvNPmx+7MG0ID5nqW6Z1LSKoCd5+N1PNlR9pIJBOlS6DiNTKeTxE9xuQdYwey1TBS0uaug8m65ogZiMb/fcgDLKolQahpYqhrw4IIDwPEORdZ/e9RnzTxX8z0hVDPXrkQV89wainyZ/PB1xBFVvaLZhDxcgzLpMzicCvowI5GROR8R3MGx3nV5YWcOSg4mBKXgTkPioQ68lXAtlaJ0yEyVOrVPt6WUJ3mVAWl1xPTXbJlq/GV1k+AtbfcfEqJPS3NAfJzhzRAh9gjiqTRNl7miBpBZ0DUVGyZahEPyMyNE6GEYZUmqWlHaXSxz4tzc=
  app: habitualize-api
  on:
    repo: jrvscm/habitualize-api
